# Generated by Django 4.2.8 on 2024-01-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_bill_train_details_bill_train_name_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.bill',),
        ),
    ]
