# Generated by Django 4.2.8 on 2023-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                (
                    "tags",
                    models.CharField(
                        choices=[
                            ("AD", "All Day"),
                            ("BR", "Breakfast"),
                            ("LU", "Lunch"),
                            ("DN", "Dinner"),
                            ("SN", "Snacks"),
                        ],
                        default="AD",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "operating_hour",
                "verbose_name_plural": "operating_hours",
                "managed": True,
            },
        ),
    ]
