# Generated by Django 4.2.8 on 2023-12-22 10:43
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _
from datetime import time

'''
DINNER - 19:00:06 - 22:00:06
BREAKFAST - 08:30:15 - 11:00:15
LUNCH - 11:30:13 - 15:30:13
SNACKS - 16:00:18 - 18:00:18
All Day - 09:00:53 - 22:00:53
'''

def insert_operating_hours(apps, schema_editor):
    OperatingHour = apps.get_model("items", "OperatingHour")

    # Values for time ranges
    ALL_DAY_FROM = time(9, 00, 0)
    ALL_DAY_TO = time(22, 0, 30)

    BREAKFAST_FROM = time(8, 30, 15)
    BREAKFAST_TO = time(11, 0, 15)

    LUNCH_FROM = time(11, 30, 15)
    LUNCH_TO = time(15, 30, 15)

    DINNER_FROM = time(19, 0, 30)
    DINNER_TO = time(22, 0, 30)

    SNACKS_FROM = time(16, 0, 30)
    SNACKS_TO = time(18, 0, 30)

    # Insert data
    OperatingHour.objects.bulk_create(
        [
            OperatingHour(
                tags="AD",
                from_time=ALL_DAY_FROM,
                to_time=ALL_DAY_TO,
                title="All Day",
            ),
            OperatingHour(
                tags="BR",
                from_time=BREAKFAST_FROM,
                to_time=BREAKFAST_TO,
                title="Breakfast",
            ),
            OperatingHour(
                tags="LU", from_time=LUNCH_FROM, to_time=LUNCH_TO, title="Lunch"
            ),
            OperatingHour(
                tags="DN", from_time=DINNER_FROM, to_time=DINNER_TO, title="Dinner"
            ),
            OperatingHour(
                tags="SN", from_time=SNACKS_FROM, to_time=SNACKS_TO, title="Snacks"
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_operatinghour"),
    ]

    operations = [
        migrations.RunPython(insert_operating_hours),
    ]
