# Generated by Django 4.2.8 on 2023-12-22 10:43
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _
from datetime import time


def insert_operating_hours(apps, schema_editor):
    OperatingHour = apps.get_model("items", "OperatingHour")

    # Values for time ranges
    ALL_DAY_FROM = time(0, 0, 0)
    ALL_DAY_TO = time(23, 59, 59)

    BREAKFAST_FROM = time(6, 0, 0)
    BREAKFAST_TO = time(10, 0, 0)

    LUNCH_FROM = time(12, 0, 0)
    LUNCH_TO = time(14, 0, 0)

    DINNER_FROM = time(18, 0, 0)
    DINNER_TO = time(21, 0, 0)

    SNACKS_FROM = time(15, 0, 0)
    SNACKS_TO = time(18, 0, 0)

    # Insert data
    OperatingHour.objects.bulk_create(
        [
            OperatingHour(
                tags="AD",
                from_time=ALL_DAY_FROM,
                to_time=ALL_DAY_TO,
                title="All Day",
            ),
            OperatingHour(
                tags="BR",
                from_time=BREAKFAST_FROM,
                to_time=BREAKFAST_TO,
                title="Breakfast",
            ),
            OperatingHour(
                tags="LU", from_time=LUNCH_FROM, to_time=LUNCH_TO, title="Lunch"
            ),
            OperatingHour(
                tags="DN", from_time=DINNER_FROM, to_time=DINNER_TO, title="Dinner"
            ),
            OperatingHour(
                tags="SN", from_time=SNACKS_FROM, to_time=SNACKS_TO, title="Snacks"
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_operatinghour"),
    ]

    operations = [
        migrations.RunPython(insert_operating_hours),
    ]
