# Generated by Django 4.2.8 on 2023-12-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.FloatField(default=18),
        ),
    ]
