# Generated by Django 4.2.8 on 2023-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='customer name')),
                ('mobile', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='customer mobile no')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'managed': True,
            },
        ),
    ]
