# Generated by Django 4.2.8 on 2024-01-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0002_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='train_details',
        ),
        migrations.AddField(
            model_name='bill',
            name='aggregator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='aggregators.aggregator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('upi', 'card'), ('card', 'upi')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='train_name',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='train_number',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='orders.order'),
        ),
    ]
