# Generated by Django 4.2.8 on 2024-01-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='train_details',
        ),
        migrations.AddField(
            model_name='bill',
            name='train_name',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='train_number',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
    ]
