# Generated by Django 4.2.8 on 2024-01-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_bill_train_details_bill_aggregator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='train_name',
            new_name='train_details',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='train_number',
        ),
    ]
