# Generated by Django 4.2.8 on 2024-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_bill_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='train_details',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
